
<div id="content_params" class="cm-tabs hidden">
	<fieldset>
		<h2 class="subheader">Фильтры</h2>
        	<a href="show" class="showAllParams">Показать все</a> / <a href="hide" class="showAllParams">Скрыть все</a><br /><br />
            <div class="clear" style="border-bottom:1px dashed #ccc;"></div>
			 <?  
			 	$i=0;
				foreach($vars['params'] as $row)
				{
					if($row['sub']==0)
					{
						echo'<div class="params_group">';
						$cheked="";
						if(isset($vars['params_set']))
						{
							foreach($vars['params_set'] as $row3)
							{
								if($row3['params_id']==$row['id']){$cheked="checked='checked'";break;}
								else $cheked="";
							}
						}
						echo"
							 <label for='{$row['id']}' onclick=\"showParams({$row['id']})\" title='Показать/Скрыть'><b>{$row['name']}</b></label><br />
							 <div id=\"params_group{$row['id']}\">";
						$cheked="";
						foreach($vars['params'] as $row2)
						{
							if($row2['sub']==$row['id'])
							{
								if(isset($vars['params_set']))
								{
									foreach($vars['params_set'] as $row3)
									{
										if($row3['params_id']==$row2['id']){$cheked="checked='checked'";break;}
										else $cheked="";
									}
								}
								echo"&nbsp;&nbsp;&nbsp;<input type='checkbox' value='{$row2['id']}' $cheked class='param{$row['id']}' id='param{$row2['id']}' name='params[]' />
									 <label for='param{$row2['id']}'>{$row2['name']}</label><br />";
							}
						}
						echo'</div></div>';
						
						if($i==3)
						{
							$i=-1;
							echo'<div class="clear" style="border-bottom:1px dashed #ccc;"></div>'	;
						}
						$i++;
					}
				}
			?>
	</fieldset>
</div>