<span class="action-add" style="margin:8px 28px 8px 8px;"> <a href="#" id="addprice"<? if(isset($vars['type'])&&$vars['type']=='add')echo' rel="add"';?>>Добавить цену</a> </span>

<label for="one_price">Единная цена</label>
<input type="checkbox" name="one_price" id="one_price" value="1" <? if((isset($vars['edit']['one_price'])&&$vars['edit']['one_price']==1)||(isset($vars['type'])&&$vars['type']=='add'))echo' checked="checked"';?> />

    <table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort" id="price_tb" style="margin-top: 10px;">
        <tr class="noDrop">
        	<th width="25"></th>
            <th>Артикул</th>
            <th>Цена</th>
            <th title="Цена закупочная">Цена закуп.</th>
            <th>Скидка</th>
            <th>Наценка</th>
            <th>Ед. из.</th>
            <th>На складе</th>
            <th>Тип цены</th>
            <th width="150">&nbsp;</th>
        </tr>
        <tbody id="load_price">
        <?php echo $vars['price']?>
        </tbody>
    </table>