<div id="cart_popup" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="width:1010px; left:38%;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel"><?=$vars['translate']['orders']?></h3>
  </div>
  <div class="modal-body" id="cart_content">
  	
  </div>
  <div class="modal-footer">
    <button class="close_m" data-dismiss="modal"><?=$vars['translate']['continue_shopping']?></button>
	<a href="<?=LINK?>/orders/all" class="submit"><?=$vars['translate']['to_order']?></a>
  </div>
</div>