<?php 
echo '<h1 class="title2">'.$vars['translate']['orders'].'</h1>';
echo $vars['message'];
if(count($vars['product'])!=0&&!isset($vars['send']))
{
	?>
    <script type="text/javascript">
		$(document).ready(function(){$("#formID").validationEngine();});
    </script>
	<form method="post" id="update_order" action="<?=LINK?>/orders/all">
		<table width="100%" class="orders2" cellpadding="0" cellspacing="0">
        <tr>
            <th style="width:50px;"><?=$vars['translate']['photo']?></th>
            <th><?=$vars['translate']['title']?></th>
            <th style="width:120px;"><?=$vars['translate']['size']?></th>
            <th style="width:150px;"><?=$vars['translate']['amount']?></th>
            <th style="width:120px;"><?=$vars['translate']['price']?></th>
            <th style="width:120px;"><?=$vars['translate']['sum']?></th>
            <th style="width:35px;"></th>
        </tr>
        <?
			$i=0;
			$summa2=0;
			$summa3=0;
			foreach($vars['product'] as $row)
			{
				//if($row['discount']==0)$row['discount']=$vars['discount'];
				$price = Numeric::viewPrice($row['price'], $row['discount']);
				$summa = Numeric::formatPrice($price['cur_price']*$row['amount']);
				$summa2+=$price['cur_price']*$row['amount'];
				$summa3+=$row['price']*$row['amount'];
				
				if(file_exists($row['photo']))$src='<img alt="'.$row['name'].'" title="'.$row['name'].'" src="/'.$row['photo'].'" style="width:50px;" />';
				else $src='<img alt="" src="/files/default.jpg" style="width:50px;" />';
				echo"
				<tr>
					<td><a href='".LINK."/product/{$row['url']}'>$src</a></td>
					<td>
						<a href='".LINK."/product/{$row['url']}'>{$row['name']}</a>
					</td>
					<td>{$row['size']}</td>
					<td width='100'>						
						<div class='productin-count'>
							
							<input type='text' id='cnt{$i}' value='{$row['amount']}' max='1000' class='amount' name='amount[]' />
							<a href='javascript:void(0);' class='countchange cnt-up' rel='cnt{$i}'>&nbsp;</a>
							<a href='javascript:void(0);' class='countchange cnt-down' rel='cnt{$i}'>&nbsp;</a>
						</div>

						<input type='hidden' value='{$row['cart_id']}' name='id[]' />
					</td>
					<td class='price'>
						{$price['price']} <span>{$price['old_price']}</span> 
					</td>
					<td class='price'>
						<font style='font-size:18px;'>{$summa}</font>
					</td>
					<td><a href='".LINK."/orders/all/del/{$row['cart_id']}' title='".$vars['translate']['delete']."'><img src='/images/del2.png' /></a></td>
				</tr>";
				$i++;	
			}
			
		?>
            <tr style="background-color:transparent; border-top:2px solid #000;" id="">
            	<td style="text-align:left; padding:0; border:none;" colspan="3">
                	<a href="<?=$_SESSION['catalog_contin']?>" class="contin"><?=$vars['translate']['continue_shopping']?></a>
                </td>
				<td colspan="3" class="total_cart" style="padding:10px 5px; border:none;">
                    <div class="total_cart" id="total_cart"><?=$vars['translate']['all2']?>: <?=Numeric::formatPrice($summa2)?></div>
                    <div id="deliver_price"></div>
                </td>
                <td></td>
			</tr>
        </table>
	</form>	
	 
	<div id="sign_up" style="width:791px; margin:30px auto;">
    <div class="title2">Информация о заказе</div>
	<form action="<?=LINK?>/orders/all/send" method="post" id="formID">
    <input type="hidden" name="report" value="" />
    <table>
    	<tr>
        	<td style="padding-right:200px;" valign="top">
            	
                <label for="name_save"><?=$vars['translate']['fio']?>  <span style="color:#F00">*</span>:</label>
                <input type="text" name="name_sign" size="30" id="name_save" class="validate[required]" value="<? if(isset($vars['user_info']['name']))echo $vars['user_info']['name']?>" />
                
                <label for="email_save"><?=$vars['translate']['email']?>  <span style="color:#F00">*</span>:</label>
                <input type="text" name="email_sign" size="30" id="email_save" class="validate[required,custom[email]]" value="<? if(isset($vars['user_info']['email']))echo $vars['user_info']['email']?>" />

                <label for="phone_save" style="width:200px;"><?=$vars['translate']['phone']?>  <span style="color:#F00">*</span>:</label>
                <input type="tel" title="Формат номера телефона: +99(099)999-99-99" name="phone_sign" size="30" id="phone_save" class="validate[required,custom[phone]]" value="<? if(isset($vars['user_info']['phone']))echo $vars['user_info']['phone']?>" />     
        		
                <label for="address"><?=$vars['translate']['address']?>:</label>
                <input type="text" name="address_sign" size="30" id="address" value="<? if(isset($vars['user_info']['address']))echo $vars['user_info']['address']?>" />
			</td>
            <td valign="top">          
                <?
					if(isset($vars['delivery'])&&count($vars['delivery'])!=0)
					{
						echo'<label for="delivery" style="width:200px;">'.$vars['translate']['delivery'].':</label>
							 <select name="delivery" id="delivery" style="width:200px;">
						<option value=""></option>';
						
						$sub_all='';
						foreach($vars['delivery'] as $row)
						{
							if($row['sub']==0)
							{
								$price='';
								if($row['price']!=0.00)
								{
									$price = Numeric::viewPrice($row['price']);
									$price=" +".$price['price'];
								}
								echo'<option value="'.$row['id'].'">'.$row['name'].' '.$price.'</option>';
								
								$sub='';
								foreach($vars['delivery'] as $row2)
								{
									if($row['id']==$row2['sub'])
									{
										$sub.='<option value="'.$row2['name'].'">'.$row2['name'].'</option>';
									}
								}
								
								if($sub!='')
								{
									$sub_all.='<div id="delivery'.$row['id'].'">
												<label for="deliv'.$row['id'].'" style="width:200px; margin-top:10px;">'.$vars['translate']['choose_point'].':</label>
											    <select name="delivery'.$row['id'].'" id="deliv'.$row['id'].'" style="width:200px;" class="validate[required]">'.$sub.'</select>
											   </div>';
								}
							}
						}
						echo'</select>
						<div id="load_delivery">'.$sub_all.'</div>
						';
					}
						
					if(isset($vars['payment'])&&count($vars['payment'])!=0)
					{
						echo'<label for="delivery" style="width:200px; margin-top:10px;">'.$vars['translate']['payment'].':</label>
							<select name="payment" id="payment" style="width:200px;">
						<option value=""></option>';
						foreach($vars['payment'] as $row)
						{
							echo'<option value="'.$row['id'].'"';if(false)echo' selected';echo'>'.$row['name'].'</option>';
						}
						echo'</select>';
					}
				?>
                
                
                
                <label for="captcha" style="width:200px; margin:25px 0 10px 0;"><?=$vars['translate']['enter_code']?></label>
                <img src="/captcha" style="float:left;" /><input type="text" name="captcha" size="30" style="width:105px;" id="captcha" value="" class="validate[required,ajax[ajaxName]]" />
		
			</td>
         </tr>
       </table>     
		
		<label for="comment" style="width:200px;"><?=$vars['translate']['comments_order']?>:</label>
		<textarea rows="5" cols="45" id="comment" name="text" style="width:730px;"></textarea>
		<br />
        <div style="margin:10px 0; color:#F00;"><?=$vars['translate']['required']?></div>
		<input type="submit" name="order" value="<?=$vars['translate']['to_order']?>" class="submit2" />
	</form>
	</div>
<?
}
else{
	if($vars['message']=="")echo"<h3 align='center'>".$vars['translate']['cart_empty']."</h3>";
}
?>	