<div id="cat_menu">
    <ul>
    <?
			$menu='';
			$i=0;
			$cnt=count($vars['menu'])-1;
            foreach($vars['menu'] as $row)
            {
				if($row['sub']==0)
				{
                    $sub = '';
                    foreach($vars['menu'] as $row2)
                    {
                        if($row2['sub']==$row['id'])
                        {
                            $pos = strpos($row2['url'], "http://");
                            if($pos !== false)$link=$row2['url'].'" target="_blank" rel="nofollow';
                            else $link=LINK."/catalog/".$row2['url'];
                            $sub.='<li><a href="'.$link.'"> • '.$row2['name'].'</a></li>';
                        }
                    }
					
					$pos = strpos($row['url'], "http://");
					if($pos !== false)$link=$row['url'].'" target="_blank" rel="nofollow';
					else $link=LINK."/catalog/".$row['url'];
					
					$style='';
					if($i==$cnt)$style='border-bottom:none;';
					
					$menu.='<li>
						    	<a href="'.$link.'">
									<span>'.$row['name'].'</span>
								</a>';
                    if($sub!='')
					{
						$menu.='<ul>'.$sub.'</ul><span class="line_menu"></span>';
					}
					$menu.='</li>';
					
					$i++;
				}
            }
			echo $menu;
        ?>
    </ul>
</div>