<div id="inform" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="width:300px; left:57%;">
  <form method="post" action="<?=STRING::getUrl3('inform');?>inform" id="inform_form">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Сообщить о наличии</h3>
  </div>
  <div class="modal-body">
  	<div id="inform_message" class="err"></div>
  	<input type="text" name="inform_name" value="" placeholder="Ваш имя" required="required" />
    <input type="text" name="inform_email" value="" placeholder="Ваш E-mail" required="required" />
    <input type="text" name="inform_phone" value="" placeholder="Ваш телефон" required="required" />
    <input type="hidden" name="inform_id" id="inform_id" value="" />
  </div>
  <div class="modal-footer" style="padding:17px 33px;">
    <input type="submit" name="send_inform" value="<?=$vars['translate']['send_message']?>" class="submit" />
  </div>
  </form>
</div>