<?
	if(file_exists($row['photo']))$src='<img alt="'.$row['name'].'" title="'.$row['name'].'" src="/'.$row['photo'].'" />';
	else $src='<img alt="" src="/files/default.jpg" />';
	
	$price=Numeric::viewPrice($row['price'], $row['discount']);
	
	if(file_exists(substr(IMAGES,1).'status'.$row['status_id'].'.png'))$status='<img src="'.IMAGES.'status'.$row['status_id'].'.png" class="status" />';
	else $status='';
	
	$style='';
	if($i==3)
	{
		//$style=' style="margin-right:0;"';
		$i=-1;	
	} 
?>
    <div class="product"<?=$style?> id="id_<?=$row['id']?>">
    	<?=$status;?>
        <? if(isset($del_compare))echo $del_compare;?>
        <div class="border_product"></div>
		<div class="photo_product">
			<a href="<?=LINK?>/product/<?=$row['url']?>" title="<?=$row['name']?>"><?=$src?><span class="border_cat"></span></a>
		</div>		
		<div class="info_product">
			<div class="name_product">
            	<a href="<?=LINK?>/product/<?=$row['url']?>" title="<?=$row['name']?>"><?=$row['name']?></a>
                
            </div>

            <div class="prod_price"><?=$price['price'].$price['old_price'];?></div>
            
            <div class="clear"></div>
		</div>
        <div class="clear"></div>
       
	</div>