<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#mycarousel').jcarousel({
            auto: 3,
            autoPlay: 2000,
            scrollAfterAmount: 3,
            scrollInc: 3,
            wrap: 'circular',
            scroll: 1,
            initCallback: mycarousel_initCallback
        });

<?
if (isset($vars['show_video'])) {
    echo"show_video();";
}
?>

    });
</script>

<?
//include"fast_order.phtml";
include"follow.phtml";
?>
<div id="curr_cat" title="licat_<?= $vars['product']['catalog_id'] ?>"></div>
<input type="hidden" id="product_id" value="<?= $vars['product']['id'] ?>" />
<div class="product_in" id="MessForPrint">
    <?
    $price = Numeric::viewPrice($vars['product']['price'], $vars['product']['discount']);

    if (isset($vars['message']))
        echo $vars['message'];

    $more_photo = '';
    if ($vars['product']['photo'] != '' && file_exists($vars['product']['photo'])) {
        $gab = getimagesize(str_replace('_s', '', $vars['product']['photo']));
        $class = '';
        if ($gab[0] > 390)
            $class = '';
        $src = '<div id="img_load">
					  <a href="/' . str_replace('_s', '', $vars['product']['photo']) . '" title="' . $vars['product']['name'] . '"  class="easyzoom" rel="lightbox">
						<img src="/' . str_replace('_s', '', $vars['product']['photo']) . '" alt="' . $vars['product']['name'] . '" />
					  </a>
				  </div>';
        //$src.='<a href="/'.str_replace('_s','',$vars['product']['photo']).'" rel="lightbox"><img src="'.IMAGES.'zoom.png" id="zoom" /></a>';

        $more_photo = '<li>
							<a href="/' . str_replace('_s', '', $vars['product']['photo']) . '" title="' . $vars['product']['name'] . '" class="load_more_photo">
								<img src="/' . $vars['product']['photo'] . '" alt="' . $vars['product']['name'] . '" />
								<span class="border_cat hov_border"></span>
							</a>
						 </li>';
    }
    else
        $src = '<img src="/files/default.jpg" />';
    ?>
    <h1 class="title2"><?= $vars['product']['name'] ?></h1>
    <div class="photoblock">
        <?
        echo $src;
        if (isset($vars['photo'][0]['id'])) {
            echo'<div class="more-photo"><ul id="mycarousel" class="jcarousel jcarousel-skin-tango">';
            echo $more_photo;
            $i = 1;
            foreach ($vars['photo'] as $row) {
                echo'<li>
								<a href="/' . str_replace('_s', '', $row['photo']) . '" title="' . $row['name'] . '" class="load_more_photo" id="extra_photo' . $row['id'] . '">
									<img src="/' . $row['photo'] . '" alt="' . $vars['translate']['photo'] . ' ' . $i . ' ' . $vars['product']['name'] . '" title="' . $vars['translate']['photo'] . ' ' . $i . '" />
									<span class="border_cat"></span>
								</a>
							 </li>';
                $i++;
            }
            echo'<div class="clear"></div></ul></div>';
        }
        ?>
    </div>
    <div id="product_right">

        <div style="width:505px; float:left;">
            <input type="hidden" id="photo_basket" value="" />
            <?
            if (isset($vars['colors']) && count($vars['colors']) != 0) {
                echo'<label>Выберите цвет:</label><br />
							 <div class="paramchoose" id="block_colors">';
                foreach ($vars['colors'] as $row) {
                    $selected = '';
                    if (!isset($vars['colors'][1]))
                        $selected = 'selected';

                    $style = '';
                    $popover = '<div class="color_picker" style="background-color: #' . $row['rgb'] . ';"></div>';
                    if ($row['photo'] != '' && file_exists($row['photo'])) {
                        $style = 'background-image:url(/' . $row['photo'] . ');';
                        $popover = '<br /><img src="/' . $row['photo'] . '" alt="" />';
                    }
                    echo '<div class="param-sel color_select ' . $selected . '" id="param-' . $row['id'] . '" style="background-color: #' . $row['rgb'] . ';' . $style . '">
								  	  <div class="popover fade top in popover2">
										<div class="arrow"></div>
										<div class="popover-content">' . $row['name'] . $popover . '</div>
									  </div>
								  </div>';
                }
                echo'</div>';
            } 

            if (isset($vars['sizes']) && count($vars['sizes']) != 0) {
                echo'<label>Выберите размер:</label><br />
							 <div class="paramchoose" id="block_sizes">';
                foreach ($vars['sizes'] as $row) {
                    $selected = '';
                    if (!isset($vars['sizes'][1]))
                        $selected = 'selected';
                    echo '<div class="param-sel size_select ' . $selected . '" id="param-' . $row['id'] . '">' . $row['name'] . '</div>';
                }
                echo'</div>';
            }
            ?>
            <div class="order-block">
                <div class="prod_price" id="total"><?= $price['price']; ?> <?= $price['old_price']; ?></div>
                <?
                if ($vars['product']['brend_id'] == 1 || $vars['product']['brend_id'] == 8) {
                    echo'
                             <noindex><button class="buy" id="price_id" name="' . $vars['product']['price_id'] . '" type="button">' . $vars['translate']['buy'] . '</button></noindex>
                             <div class="status_product">' . $vars['product']['brend'] . '</div>';
                } elseif ($vars['product']['brend_id'] == 2) {
                    echo'
                             <noindex><a href="#inform" data-toggle="modal" class="buy nostock" rel="' . $vars['product']['id'] . '">Сообщить</a></noindex>
                             <div class="status_product not_available">' . $vars['product']['brend'] . '</div>';
                } elseif ($vars['product']['brend_id'] == 3) {
                    echo'
                             <noindex><button class="buy expect" id="price_id" name="' . $vars['product']['price_id'] . '" type="button">Заказать</button></noindex>
                             <div class="status_product expected">' . $vars['product']['brend'] . '</div>';
                }

                echo $vars['rating'];
                //if($vars['product']['brend']!='')echo'<div class="stock" id="stock'.$vars['product']['brend_id'].'">'.$vars['product']['brend'].'</div>';     
                ?>

            </div>
            <div class="fav_block">
                <a href="#" class="add_compare link_gray bwWrapper" rel="<?= $vars['product']['id'] ?>"><i><img src="<?= IMAGES ?>compare.png"></i>сравнить</a>
                <a href="#" class="add_fav link_gray bwWrapper" rel="<?= $vars['product']['id'] ?>"><i><img src="<?= IMAGES ?>fav.png"></i>в закладки</a>
                <a href="#product_right" onclick="show_video()" class="add_video link_gray bwWrapper" rel="<?= $vars['product']['id'] ?>"><i><img src="<?= IMAGES ?>video.png"></i>видео</a>

                <a href="#follow_price" data-toggle="modal" class="follow_price link_gray" rel="<?= $vars['product']['id'] ?>">следить за ценой</a>
            </div>
        </div>
        <div class="delivery_block">
            <div class="delivery_block_in">
                <?= htmlspecialchars_decode($vars['delivery']['body']); ?>
            </div>
        </div>
        <br class="clear" />
        <div id="tabs">
            <ul id="tabs_ul">
                <li onclick="showTab('tab_all')" class="hov_tab">Все</li>
                <li onclick="showTab('Featured')">Описание</li>
                <li onclick="showTab('Featured2')">Характеристики</li>
                <li onclick="showTab('Comments')">Отзывы</li>
                <li onclick="showTab('Video')">Видео</li>
            </ul>
            <br class="clear" />
            <div id="tab_all" class="hov_tab div_tab">
                <div class="div_over">
                    <h4>Описание</h4>
                    <?= htmlspecialchars_decode($vars['product']['body']) ?>
                </div>
                <div class="div_over">
                    <h4>Характеристики</h4>
                    <?= htmlspecialchars_decode($vars['product']['body2']) ?>
                </div>

                <div class="div_over">
                    <h4>Видео</h4>
                    <?= htmlspecialchars_decode($vars['product']['body3']) ?>
                </div>
                <div class="div_over">
                    <h4>Отзывы</h4>
                    <?php
                    if (isset($_SESSION['user_comments']['photo']) && $_SESSION['user_comments']['photo'] != '')
                        $src = $_SESSION['user_comments']['photo'];
                    else
                        $src = '/files/default.gif';


                    echo'<div id="comment_list">';

                    foreach ($vars['comments2'] as $row) {
                        if ($row['photo'] != '')
                            $src = $row['photo'];
                        else
                            $src = '/files/default.gif';

                        $answer = '';
                        if ($row['text2'] != '') {
                            if ($row['moderator_id'] != 0 && file_exists("files/moderators/{$row['moderator_id']}_s.jpg"))
                                $src2 = "/files/moderators/{$row['moderator_id']}_s.jpg";
                            else
                                $src2 = '/files/default.gif';

                            $answer = '
										<div class="comment_record answer_comment">
											<div class="photo_comment"><img src="' . $src2 . '" width="50" /></div>
											<div class="info_comment">
												<div class="title_comment">' . $row['author2'] . ', ' . Date::date_view($row['date'], "dd.mm.YY, hh:ii") . '</div>
												<div class="text_comment">' . $row['text2'] . '</div>
												
											</div>
											<div class="clear"></div>
										</div>
										';
                        }

                        if (file_exists("files/comments/{$row['id']}.jpg"))
                            $src3 = '<img src="/files/comments/' . $row['id'] . '.jpg" class="photo_comment2" /><div class="clear"></div>';
                        else
                            $src3 = '';
                        echo'
									<div class="comment_record">
										' . $src3 . '
										<div class="photo_comment"><img src="' . $src . '" width="50" /></div>
										<div class="info_comment">
											<div class="date_comment">' . Date::date_view($row['date'], "dd.mm.YY, hh:ii") . '</div>
											<div class="text_comment"><span class="title_comment">' . $row['author'] . '. </span>' . $row['text'] . '</div>
											
										</div>
										<div class="clear"></div>
										
									</div>' . $answer;
                    }

                    echo'</div>';
                    ?>
                </div>
                <div class="clear"></div>
            </div>
            <div id="Featured" class="div_tab"><?= htmlspecialchars_decode($vars['product']['body']) ?></div>
            <div id="Featured2" class="div_tab">
                <?
                echo'<div class="params_block">';
                foreach ($vars['params'] as $row) {
                    echo'<div><b>' . $row['sub_name'] . '</b>: &nbsp;' . $row['name'] . '</div>';
                }
                echo'</div>';
                ?>
            </div>
            <div id="Comments" class="div_tab"><? echo $vars['comments']; ?></div>
            <div id="Video" class="div_tab"><?= htmlspecialchars_decode($vars['product']['body3']) ?></div>
            <div class="clear"></div>
        </div>
    </div>

    <div class="clear"></div>
    <?
    if (isset($vars['other'][0])) {
        if (isset($vars['other'][4])) {
            echo'<script type="text/javascript">
							jQuery(document).ready(function(){
								jQuery("#mycarousel2").jcarousel({
										auto: 3,
										autoPlay:2000,
										scrollAfterAmount:3,
										scrollInc:3,
										wrap: "circular",
										scroll:1,
										initCallback: mycarousel_initCallback
									});
							});
							</script>';
        }
        echo'<div class="title_other">' . $vars['translate']['other_product'] . '</div>
					 <div class="product_block">
					 	<ul id="mycarousel2" class="jcarousel jcarousel-skin-tango">';
        $i = 0;
        foreach ($vars['other'] as $row) {
            echo'<li>';
            include "product.phtml";
            echo'</li>';
            $i++;
        }
        echo'</ul><div class="clear"></div></div>';
    }
    ?> 
</div>