<?
	$site_url="http://{$_SERVER['HTTP_HOST']}/";
	echo'<?xml version="1.0" encoding="utf-8"?>';
?>
	<!DOCTYPE yml_catalog SYSTEM "shops.dtd">
	<yml_catalog date="<?=date('Y-m-d H:i:s')?>">
	<shop>
	  <name><?=$vars['sitename']?></name>
	  <company><?=$vars['sitename']?></company>
	  <url><?=$site_url?></url>
	 <currencies>
	  <currency id="UAH" rate="1"/>
	</currencies>
	<categories>
    <?
		foreach($vars['catalog'] as $row)
		{
			if($row['sub']==0)
			{
				$descr_cat = String::sanitize($row["name"], true);
				echo'<category id="'.$row["id"].'">'.$descr_cat.'</category>';
				foreach($vars['catalog'] as $row2)
				{
					if($row['id']==$row2['sub'])
					{
						$descr_cat = String::sanitize($row2["name"], true);
						echo'<category id="'.$row2["id"].'" parentId="'.$row["id"].'">'.$descr_cat.'</category>';
						
						foreach($vars['catalog'] as $row3)
						{
							if($row2['id']==$row3['sub'])
							{
								$descr_cat = String::sanitize($row3["name"], true);
								echo'<category id="'.$row3["id"].'" parentId="'.$row2["id"].'">'.$descr_cat.'</category>';
							}
						}
					}
				}
			}
			//catalog_market($id_cat);
		}
	?>
	</categories>
    <offers>
	<?	
		$i=1;
        foreach($vars['product'] as $row)
        {
            $url = $site_url."product/".$row['url'];
           	$cat_id=getRootCat($row["catalog_id"], $vars['catalog']);
            $img='';
            if(file_exists($row['photo']))$img=$site_url.$row['photo'];
            $text = String::sanitize($row["body"], true);
            $name = String::sanitize($row["name"], true);
			$price=Numeric::viewPrice($row['price'], $row['discount']);
			
            if($cat_id!=''&&$row["price"]!=''&&$name!='')
            echo '
            <offer id="'.$row["id"].'" bid="'.$i.'" available="true">
                <url>'.$url.'</url>
                <price>'.$price['cur_price'].'</price>
                <currencyId>UAH</currencyId>
                <categoryId>'.$cat_id.'</categoryId >
                <picture>'.$img.'</picture>
                <delivery>true</delivery>
                <name>'.$name.'</name>
                <description>'.strip_tags($text).'</description>
            </offer>
            ';
			$i++;
        }
    ?>
    </offers>
</shop>
</yml_catalog>