<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="ru" />
    <meta name="keywords" content="Админ панель Skylogic—CMS" />
    <meta name="description" content="Админ панель Skylogic—CMS" />
    <title>Админ панель Skylogic—CMS</title>
    <link rel="shortcut icon"  href="/tpl/admin/images/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="/tpl/admin/css/style.css" />
    <link rel="stylesheet" type="text/css" href="/tpl/admin/css/jquery.notification.css" />
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="/tpl/admin/css/jquery.simple-dtpicker.css" />

    <script type="text/javascript" src="/tpl/admin/js/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="/tpl/admin/js/jquery-ui-1.10.3.custom.js"></script>
    <script type="text/javascript" src="/tpl/admin/js/base.js"></script>
    <script type="text/javascript" src="/tpl/admin/js/jquery.tablednd_0_5.js"></script>
    <script type="text/javascript" src="/tpl/admin/js/ajax.js"></script>
    <script type="text/javascript" src="/tpl/admin/js/jquery.cookie.js"></script>
    <script type="text/javascript" src="/tpl/admin/js/autoresize.jquery.js"></script>
    <script type="text/javascript" src="/tpl/admin/js/jquery.simple-dtpicker.js"></script>
</head>
<body style="background-color: #fff;">
    <div class="loadStat"><?=$vars['graph']?></div>
</body>
</html>