<?
echo'
	<tr>
		<th width="50">ID</th>
		<th width="100">Фото</th>
		<th>Товар</th>
		<th width="100">Кол-во</th>
		<th width="100">Скидка</th>
		<th width="100">Цена ('.$vars['currency']['icon'].')</th>
		<th width="100">Сумма</th>
		<th width="100">&nbsp;</th>
	</tr>';
	foreach($vars['product'] as $row)
	{
		if($row['photo_basket']!=''&&file_exists($row['photo_basket']))
		{
			$src=$row['photo_basket'];
		}
		elseif(file_exists($row['photo']))
		{
			$src=$row['photo'];
		}
		else $src='files/default.jpg';
		
		echo'<tr>
				<td><span>'.$row['product_id'].'</span></td>
				<td><a href="/product/'.$row['url'].'" target="_blank"><img src="/'.$src.'" width="100" /></a></td>
				<td><input type="text" name="name[]" value="'.$row['name'].'" size="40" /></td>
				<td><input type="text" name="amount[]" value="'.$row['amount'].'" size="3" style="text-align:center;" /></td>
				<td><input type="text" name="discount[]" value="'.$row['discount'].'" size="3" style="text-align:center;" /> %</td>
				<td><input type="text" name="price[]" value="'.$row['price'].'" size="10" /></td>
				<td>'.$row['sum'].'</td>
				<td width="10%">
					<input type="hidden" name="product_id[]" value="'.$row['id'].'" />
					<ul class="cm-tools-list tools-list">
						<li><a href="/admin/orders/edit/'.$vars['order_id'].'/del/'.$row['id'].'" class="cm-confirm">Удалить</a></li>
					</ul>
				</td>
			</tr>';
	}
	//echo'Итого: '.$vars['total'];
?>