<div class="cm-notification-container"></div>
<div id="message"><?=$vars['message']?></div>
<div>
	<div class="clear mainbox-title-container">
		<div class="tools-container"><span class="action-add"> <a href="/admin/<?=$vars['action'].$vars['path']?>/add_provider">Добавить</a> </span> </div>
		<h1 class="mainbox-title float-left"><?=$vars['name']?></h1>
	</div>
	<div class="mainbox-body">
		<div id="ds_15014" class="clear"></div>
		<div id="content_manage_users">
			<form name="userlist_form" method="post" action="/admin/<?=$vars['action'].$vars['path']?>">
				<div id="pagination_contents">
					
					<div class="items-container multi-level">
						<table width="100%" cellspacing="0" cellpadding="0" border="0" class="table table-fixed hidden-inputs tb_sort">
							<tr>
								<th width="30">ID</th>
								<th width="180">Название</th>
								<th width="80">&nbsp;</th>
							</tr>
							<?php
								foreach($vars['list'] as $row)
								{
									echo'<tr>
											<td><input type="hidden" class="check-item" value="'.$row['id'].'" name="id[]" /><span>'.$row['id'].'</span></td>
											<td><input type="text" value="'.$row['name'].'" name="name[]" class="input-text-large"></td>
											<td style="text-align:center;">
												<ul class="cm-tools-list tools-list">
													<li><a href="/admin/'.$vars['action'].'/delete/'.$row['id'].$vars['path'].'" class="cm-confirm">Удалить</a></li>
												</ul>
											</td>
										</tr>';
								}
							?>
						</table>
					</div>
				</div>
				<div class="buttons-container buttons-bg">
					<div class="cm-buttons-placeholder">
						<div class="float-left">
							<span class="submit-button cm-button-main">
								<input type="submit" value="Сохранить" name="update" class="">
							</span>
						</div>
					</div>
					<div class="cm-buttons-floating hidden"></div>
				</div>
				<input type="hidden" value="meta" id="action" />
				<input type="hidden" value="redirects" id="action2" />
			</form>
			</div>
		</div>
	</div>
</div>